### ISSUE TITLE
files

### ISSUE THREAD

**Issue by abdulhameednabhan** [alisonmitchell/Stock-Prediction#1]
Hi, I am facing problems in installing packages regarding web scraping and I need to work on the files, they are very wonderful. Thank you for that great work. Can you attach all the csv and Pkl files thatit usre in the project so that I can work on them initially

**Comment by alisonmitchell** [comment]
Hi, glad you like the project! I have attached the files which you may find useful.


[stock_data.zip](https://github.com/alisonmitchell/Stock-Prediction/files/8192785/stock_data.zip)
