### ISSUE TITLE
bad accuracy

### ISSUE THREAD

**Issue by abdulhameednabhan** [alisonmitchell/Stock-Prediction#2]
Hello Alison, I have a problem. Do you notice that the error function is too big? The evaluation of the model is bad, but when I draw the test and prediction data, the shape is good. Are there suggestions to improve the results or is this the maximum possible?

**Comment by alisonmitchell** [comment]
Hello Abdul Hameed, thanks for getting in touch. Which notebook are you referring to? It might be that it was a small dataset or that more preprocessing should have been done on it. Grateful for any suggestions.
Thanks, 
Alison

**Comment by abdulhameednabhan** [comment]
thank you for replayig  
I'm talking about lstm  Are there suggestions for improvement? In general, what is the best model?

**Comment by alisonmitchell** [comment]
I think it would be an experiment to try a different number of hidden layers/dropouts, and change the number of epochs and batch size. I thought 64 was the optimal batch size but you could also try 32 perhaps.

**Comment by abdulhameednabhan** [comment]
thank you i try  i will keep in touch
