### ISSUE TITLE
Working Pipeline of the model

### ISSUE THREAD

**Issue by krishna-anumula** [alisonmitchell/Stock-Prediction#3]
Hi @alisonmitchell ,

Could you please give exact pipeline on how to run this with our own data.

**Comment by alisonmitchell** [comment]
Hi @krishna-anumula

Thanks for getting in touch. The project as a whole was just a learning curve in working with time series data and some NLP and text analysis. I really just started by collecting historical stock data using the Yahoo! Finance API for Technical Analysis and then moved on to investigating various ways of modelling the data for prediction. I also looked at whether news sentiment could be incorporated.

Regards
Alison
