### ISSUE TITLE
LSTM notebook logic is wrong!

### ISSUE THREAD

**Issue by keivanipchihagh** [alisonmitchell/Stock-Prediction#4]
The notebook named "Deep Learning: Long Short-Term Memory (LSTM)" has indeed a wrong logic and the results are not realistic. The problem is you created the test data and fed the model to predict the future. Well, that's the problem! You don't know the future and you can't use the test set to make the predictions. Instead, you have the first 60 data points that you use to predict the 61th. Then you use the second 60 data points (including the one you just predicted) to predict the 62th and so on. The current implementation is wrong.

**Comment by alisonmitchell** [comment]
Hi @keivanipchihagh 

Thanks very much for looking at this and sending your observations. Will close for now and update if I get a chance to revisit it.
